resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      minimumNumberOfCalls: 2
  instances:
    episodios:
      baseConfig: default
